version: '3'

services:
  redis:
    build: redis
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    restart: always

  mysql:
    build: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'dev123$$'
      MYSQL_USER: lac_dev
      MYSQL_PASSWORD: 'dev123$$'
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: '256MiB'
    restart: always

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/var/lib/mongodb
    ports:
      - "27017:27017"
    restart: always

volumes:
  redis_data:
  mysql_data:
  rabbitmq_data:
  mongodb_data:

